In [ ]:
from pathlib import Path

import polars as pl

project_path = Path.cwd() / "output" / "project"

In [ ]:
1566 + 2960 + 4314565 - 4330336

-11245

In [ ]:
patient = pl.scan_csv("/workspaces/example/data/physionet.org/files/mimiciv/3.1/hosp/patients.csv.gz")
patient.filter(pl.col("subject_id") == 10000032).collect()

shape: (1, 6)
┌────────────┬────────┬────────────┬─────────────┬───────────────────┬────────────┐
│ subject_id ┆ gender ┆ anchor_age ┆ anchor_year ┆ anchor_year_group ┆ dod        │
│ ---        ┆ ---    ┆ ---        ┆ ---         ┆ ---               ┆ ---        │
│ i64        ┆ str    ┆ i64        ┆ i64         ┆ str               ┆ str        │
╞════════════╪════════╪════════════╪═════════════╪═══════════════════╪════════════╡
│ 10000032   ┆ F      ┆ 52         ┆ 2180        ┆ 2014 - 2016       ┆ 2180-09-09 │
└────────────┴────────┴────────────┴─────────────┴───────────────────┴────────────┘

In [ ]:
icu_stay = pl.scan_csv("/workspaces/example/data/physionet.org/files/mimiciv/3.1/icu/icustays.csv.gz")

# Creatinine

In [ ]:
6634093860 - 1648126260

4985967600

In [ ]:
6637933500 - 1651965900

4985967600

In [ ]:
365.25 * 4

1461.0

In [ ]:
4985967600 / (1461 * 24 * 3600) * 4

157.99577914670317

In [ ]:
158

158

In [ ]:
labevent = pl.scan_parquet(project_path / "workspace" / "extraction" / "mimic-iv" / "3.1" / "labevents" / "labevent.parquet")
data = labevent.filter(pl.col("code").str.contains("Creatinine//")).collect()

FileNotFoundError: No such file or directory (os error 2): ...nICU-Example/output/project/workspace/extraction/mimic-iv/3.1/labevents/labevent.parquet (set POLARS_VERBOSE=1 to see full path)

This error occurred with the following context stack:
	[1] 'parquet scan'
	[2] 'filter'
	[3] 'sink'

In [ ]:
labevent.filter

In [ ]:
data.filter(pl.col("subject_id")  == 10000032)

shape: (18, 7)
┌────────────┬──────────────┬────────────────────┬───────────────┬────────────┬──────────┬─────────┐
│ subject_id ┆ time         ┆ code               ┆ numeric_value ┆ text_value ┆ hadm_id  ┆ stay_id │
│ ---        ┆ ---          ┆ ---                ┆ ---           ┆ ---        ┆ ---      ┆ ---     │
│ i64        ┆ datetime[μs] ┆ str                ┆ f32           ┆ str        ┆ str      ┆ str     │
╞════════════╪══════════════╪════════════════════╪═══════════════╪════════════╪══════════╪═════════╡
│ 10000032   ┆ 2180-03-23   ┆ mimic-iv//3.1//lab ┆ 0.4           ┆ 0.4        ┆ null     ┆ -1      │
│            ┆ 11:51:00     ┆ events//labe…      ┆               ┆            ┆          ┆         │
│ 10000032   ┆ 2180-05-06   ┆ mimic-iv//3.1//lab ┆ 0.3           ┆ 0.3        ┆ null     ┆ -1      │
│            ┆ 22:25:00     ┆ events//labe…      ┆               ┆            ┆          ┆         │
│ 10000032   ┆ 2180-05-07   ┆ mimic-iv//3.1//lab ┆ 0.3           ┆ 0.3        ┆ 22595853 ┆ -1      │
│            ┆ 05:05:00     ┆ events//labe…      ┆               ┆            ┆          ┆         │
│ 10000032   ┆ 2180-06-03   ┆ mimic-iv//3.1//lab ┆ 0.4           ┆ 0.4        ┆ null     ┆ -1      │
│            ┆ 12:00:00     ┆ events//labe…      ┆               ┆            ┆          ┆         │
│ 10000032   ┆ 2180-06-03   ┆ mimic-iv//3.1//lab ┆ 0.4           ┆ 0.4        ┆ null     ┆ -1      │
│            ┆ 12:00:00     ┆ events//labe…      ┆               ┆            ┆          ┆         │
│ …          ┆ …            ┆ …                  ┆ …             ┆ …          ┆ …        ┆ …       │
│ 10000032   ┆ 2180-08-05   ┆ mimic-iv//3.1//lab ┆ 0.6           ┆ 0.6        ┆ null     ┆ -1      │
│            ┆ 21:20:00     ┆ events//labe…      ┆               ┆            ┆          ┆         │
│ 10000032   ┆ 2180-08-06   ┆ mimic-iv//3.1//lab ┆ 0.6           ┆ 0.6        ┆ 25742920 ┆ -1      │
│            ┆ 06:36:00     ┆ events//labe…      ┆               ┆            ┆          ┆         │
│ 10000032   ┆ 2180-08-07   ┆ mimic-iv//3.1//lab ┆ 0.4           ┆ 0.4        ┆ 25742920 ┆ -1      │
│            ┆ 00:59:00     ┆ events//labe…      ┆               ┆            ┆          ┆         │
│ 10000032   ┆ 2180-08-07   ┆ mimic-iv//3.1//lab ┆ 0.4           ┆ 0.4        ┆ 25742920 ┆ -1      │
│            ┆ 06:15:00     ┆ events//labe…      ┆               ┆            ┆          ┆         │
│ 10000032   ┆ 2180-08-10   ┆ mimic-iv//3.1//lab ┆ 0.8           ┆ 0.8        ┆ null     ┆ -1      │
│            ┆ 12:00:00     ┆ events//labe…      ┆               ┆            ┆          ┆         │
└────────────┴──────────────┴────────────────────┴───────────────┴────────────┴──────────┴─────────┘

In [ ]:
for e in data.filter(pl.col("numeric_value").is_null()).iter_rows():
    print(e)

(17720947, datetime.datetime(2178, 10, 20, 12, 56), 'mimic-iv//3.1//labevents//labevent//Creatinine//mg/dL', None, '___', None, '-1')

In [ ]:
crea_directory = project_path / "workspace" /"concept" /"creatinine" / "1.0.0"

crea_paths = [str(p) for p in crea_directory.iterdir() if p.is_file()]

crea =  pl.scan_parquet(crea_paths[0])

In [ ]:
df = crea.collect()

In [ ]:
df

shape: (4_318_794, 8)
┌────────────┬────────────┬────────────┬────────────┬───────────┬──────────┬───────────┬───────────┐
│ subject_id ┆ time       ┆ code       ┆ numeric_va ┆ text_valu ┆ dataset  ┆ table     ┆ src_code  │
│ ---        ┆ ---        ┆ ---        ┆ lue        ┆ e         ┆ ---      ┆ ---       ┆ ---       │
│ i64        ┆ datetime[μ ┆ str        ┆ ---        ┆ ---       ┆ str      ┆ str       ┆ str       │
│            ┆ s]         ┆            ┆ f32        ┆ str       ┆          ┆           ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══════════╪══════════╪═══════════╪═══════════╡
│ 10000032   ┆ 2180-03-23 ┆ creatinine ┆ 0.4        ┆ 0.4       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 11:51:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 10000032   ┆ 2180-05-06 ┆ creatinine ┆ 0.3        ┆ 0.3       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 22:25:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 10000032   ┆ 2180-05-07 ┆ creatinine ┆ 0.3        ┆ 0.3       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 05:05:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 10000032   ┆ 2180-06-03 ┆ creatinine ┆ 0.4        ┆ 0.4       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 12:00:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 10000032   ┆ 2180-06-03 ┆ creatinine ┆ 0.4        ┆ 0.4       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 12:00:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …        ┆ …         ┆ …         │
│ 19999987   ┆ 2145-11-05 ┆ creatinine ┆ 0.9        ┆ 0.9       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 06:10:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 19999987   ┆ 2145-11-06 ┆ creatinine ┆ 1.0        ┆ 1.0       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 10:07:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 19999987   ┆ 2145-11-07 ┆ creatinine ┆ 0.9        ┆ 0.9       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 06:00:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 19999987   ┆ 2145-11-09 ┆ creatinine ┆ 0.9        ┆ 0.9       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 05:30:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 19999987   ┆ 2146-02-07 ┆ creatinine ┆ 1.1        ┆ 1.1       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 11:13:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
└────────────┴────────────┴────────────┴────────────┴───────────┴──────────┴───────────┴───────────┘

In [ ]:
df = df.with_columns(
    (pl.col("time").dt.epoch("s")).alias("seconds_since_epoch")
)

In [ ]:
year = patient.filter(pl.col("subject_id") == 10000032).collect()["anchor_year"][0]

In [ ]:
df.sort("seconds_since_epoch").filter(pl.col("subject_id") == 10000032)

shape: (18, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ subject_i ┆ time      ┆ code      ┆ numeric_v ┆ … ┆ dataset  ┆ table     ┆ src_code  ┆ seconds_s │
│ d         ┆ ---       ┆ ---       ┆ alue      ┆   ┆ ---      ┆ ---       ┆ ---       ┆ ince_epoc │
│ ---       ┆ datetime[ ┆ str       ┆ ---       ┆   ┆ str      ┆ str       ┆ str       ┆ h         │
│ i64       ┆ μs]       ┆           ┆ f32       ┆   ┆          ┆           ┆           ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ i64       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ 10000032  ┆ 2180-03-2 ┆ creatinin ┆ 0.4       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 663409386 │
│           ┆ 3         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆ 0         │
│           ┆ 11:51:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 10000032  ┆ 2180-05-0 ┆ creatinin ┆ 0.3       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 663793350 │
│           ┆ 6         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆ 0         │
│           ┆ 22:25:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 10000032  ┆ 2180-05-0 ┆ creatinin ┆ 0.3       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 663795750 │
│           ┆ 7         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆ 0         │
│           ┆ 05:05:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 10000032  ┆ 2180-06-0 ┆ creatinin ┆ 0.4       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 664031520 │
│           ┆ 3         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆ 0         │
│           ┆ 12:00:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 10000032  ┆ 2180-06-0 ┆ creatinin ┆ 0.4       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 664031520 │
│           ┆ 3         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆ 0         │
│           ┆ 12:00:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ 10000032  ┆ 2180-08-0 ┆ creatinin ┆ 0.6       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 664579200 │
│           ┆ 5         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆ 0         │
│           ┆ 21:20:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 10000032  ┆ 2180-08-0 ┆ creatinin ┆ 0.6       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 664582536 │
│           ┆ 6         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆ 0         │
│           ┆ 06:36:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 10000032  ┆ 2180-08-0 ┆ creatinin ┆ 0.4       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 664589154 │
│           ┆ 7         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆ 0         │
│           ┆ 00:59:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 10000032  ┆ 2180-08-0 ┆ creatinin ┆ 0.4       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 664591050 │
│           ┆ 7         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆ 0         │
│           ┆ 06:15:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 10000032  ┆ 2180-08-1 ┆ creatinin ┆ 0.8       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 664619040 │
│           ┆ 0         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆ 0         │
│           ┆ 12:00:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [ ]:
(6634093860 - 1648126260 ) / (365.25 * 24 * 3600)

157.99577914670317

In [ ]:
1566+2960+4314565

4319091

In [ ]:
crea.collect()

shape: (4_318_794, 8)
┌────────────┬────────────┬────────────┬────────────┬───────────┬──────────┬───────────┬───────────┐
│ subject_id ┆ time       ┆ code       ┆ numeric_va ┆ text_valu ┆ dataset  ┆ table     ┆ src_code  │
│ ---        ┆ ---        ┆ ---        ┆ lue        ┆ e         ┆ ---      ┆ ---       ┆ ---       │
│ i64        ┆ datetime[μ ┆ str        ┆ ---        ┆ ---       ┆ str      ┆ str       ┆ str       │
│            ┆ s]         ┆            ┆ f32        ┆ str       ┆          ┆           ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══════════╪══════════╪═══════════╪═══════════╡
│ 10000032   ┆ 2180-03-23 ┆ creatinine ┆ 0.4        ┆ 0.4       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 11:51:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 10000032   ┆ 2180-05-06 ┆ creatinine ┆ 0.3        ┆ 0.3       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 22:25:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 10000032   ┆ 2180-05-07 ┆ creatinine ┆ 0.3        ┆ 0.3       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 05:05:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 10000032   ┆ 2180-06-03 ┆ creatinine ┆ 0.4        ┆ 0.4       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 12:00:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 10000032   ┆ 2180-06-03 ┆ creatinine ┆ 0.4        ┆ 0.4       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 12:00:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …        ┆ …         ┆ …         │
│ 19999987   ┆ 2145-11-05 ┆ creatinine ┆ 0.9        ┆ 0.9       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 06:10:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 19999987   ┆ 2145-11-06 ┆ creatinine ┆ 1.0        ┆ 1.0       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 10:07:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 19999987   ┆ 2145-11-07 ┆ creatinine ┆ 0.9        ┆ 0.9       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 06:00:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 19999987   ┆ 2145-11-09 ┆ creatinine ┆ 0.9        ┆ 0.9       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 05:30:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 19999987   ┆ 2146-02-07 ┆ creatinine ┆ 1.1        ┆ 1.1       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 11:13:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
└────────────┴────────────┴────────────┴────────────┴───────────┴──────────┴───────────┴───────────┘

In [ ]:
crea.filter(pl.col("subject_id") == 12466550).collect()

shape: (14, 8)
┌────────────┬────────────┬────────────┬────────────┬───────────┬──────────┬───────────┬───────────┐
│ subject_id ┆ time       ┆ code       ┆ numeric_va ┆ text_valu ┆ dataset  ┆ table     ┆ src_code  │
│ ---        ┆ ---        ┆ ---        ┆ lue        ┆ e         ┆ ---      ┆ ---       ┆ ---       │
│ i64        ┆ datetime[μ ┆ str        ┆ ---        ┆ ---       ┆ str      ┆ str       ┆ str       │
│            ┆ s]         ┆            ┆ f32        ┆ str       ┆          ┆           ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══════════╪══════════╪═══════════╪═══════════╡
│ 12466550   ┆ 2174-09-29 ┆ creatinine ┆ 1.2        ┆ 1.2       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 10:16:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 12466550   ┆ 2174-09-29 ┆ creatinine ┆ 0.9        ┆ 0.9       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 15:37:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 12466550   ┆ 2174-09-30 ┆ creatinine ┆ 1.1        ┆ 1.1       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 03:34:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 12466550   ┆ 2174-10-01 ┆ creatinine ┆ 0.8        ┆ 0.8       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 05:35:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 12466550   ┆ 2174-10-02 ┆ creatinine ┆ 0.8        ┆ 0.8       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 07:20:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …        ┆ …         ┆ …         │
│ 12466550   ┆ 2174-10-07 ┆ creatinine ┆ 1.1        ┆ 1.1       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 06:20:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 12466550   ┆ 2174-10-08 ┆ creatinine ┆ 1.0        ┆ 1.0       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 09:15:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 12466550   ┆ 2174-10-09 ┆ creatinine ┆ 1.1        ┆ 1.1       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 10:30:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 12466550   ┆ 2174-10-10 ┆ creatinine ┆ 0.9        ┆ 0.9       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 09:50:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 12466550   ┆ 2174-10-11 ┆ creatinine ┆ 1.0        ┆ 1.0       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 05:25:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
└────────────┴────────────┴────────────┴────────────┴───────────┴──────────┴───────────┴───────────┘

In [ ]:
crea_subject = crea.filter(pl.col("subject_id") == 12466550).collect()
value = crea_subject[0]["time"][0]
charttime = value.second + value.minute * 60 + value.hour * 3600 + value.day * 3600 * 24 + value.month * 3600 * 24 * 30 + value.year * 3600 * 24 * 365
charttime

68585134560

In [ ]:
(55500 - 12480 ) / 60 /60

11.95

In [ ]:
60 * 95

5700

In [ ]:
str((12480/60 - (12480/60)%60)/60) + "h " + str((12480/60)%60) + "min"

'3.0h 28.0min'

In [ ]:
crea_subject.with_columns(((pl.col("time") - crea_subject[0]["time"][0])).alias("charttime"))

shape: (14, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ subject_i ┆ time      ┆ code      ┆ numeric_v ┆ … ┆ dataset  ┆ table     ┆ src_code  ┆ charttime │
│ d         ┆ ---       ┆ ---       ┆ alue      ┆   ┆ ---      ┆ ---       ┆ ---       ┆ ---       │
│ ---       ┆ datetime[ ┆ str       ┆ ---       ┆   ┆ str      ┆ str       ┆ str       ┆ duration[ │
│ i64       ┆ μs]       ┆           ┆ f32       ┆   ┆          ┆           ┆           ┆ μs]       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ 12466550  ┆ 2174-09-2 ┆ creatinin ┆ 1.2       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 0µs       │
│           ┆ 9         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆           │
│           ┆ 10:16:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 12466550  ┆ 2174-09-2 ┆ creatinin ┆ 0.9       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 5h 21m    │
│           ┆ 9         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆           │
│           ┆ 15:37:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 12466550  ┆ 2174-09-3 ┆ creatinin ┆ 1.1       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 17h 18m   │
│           ┆ 0         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆           │
│           ┆ 03:34:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 12466550  ┆ 2174-10-0 ┆ creatinin ┆ 0.8       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 1d 19h    │
│           ┆ 1         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆ 19m       │
│           ┆ 05:35:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 12466550  ┆ 2174-10-0 ┆ creatinin ┆ 0.8       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 2d 21h 4m │
│           ┆ 2         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆           │
│           ┆ 07:20:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ 12466550  ┆ 2174-10-0 ┆ creatinin ┆ 1.1       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 7d 20h 4m │
│           ┆ 7         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆           │
│           ┆ 06:20:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 12466550  ┆ 2174-10-0 ┆ creatinin ┆ 1.0       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 8d 22h    │
│           ┆ 8         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆ 59m       │
│           ┆ 09:15:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 12466550  ┆ 2174-10-0 ┆ creatinin ┆ 1.1       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 10d 14m   │
│           ┆ 9         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆           │
│           ┆ 10:30:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 12466550  ┆ 2174-10-1 ┆ creatinin ┆ 0.9       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 10d 23h   │
│           ┆ 0         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆ 34m       │
│           ┆ 09:50:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 12466550  ┆ 2174-10-1 ┆ creatinin ┆ 1.0       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 11d 19h   │
│           ┆ 1         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆ 9m        │
│           ┆ 05:25:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [ ]:
icustay = pl.scan_csv("/workspaces/example/data/physionet.org/files/mimiciv/3.1/icu/icustays.csv.gz", schema_overrides={"intime":pl.Datetime}).filter(pl.col("subject_id") == 12466550).collect()
icustay

shape: (2, 8)
┌────────────┬──────────┬──────────┬─────────────┬────────────┬────────────┬────────────┬──────────┐
│ subject_id ┆ hadm_id  ┆ stay_id  ┆ first_careu ┆ last_careu ┆ intime     ┆ outtime    ┆ los      │
│ ---        ┆ ---      ┆ ---      ┆ nit         ┆ nit        ┆ ---        ┆ ---        ┆ ---      │
│ i64        ┆ i64      ┆ i64      ┆ ---         ┆ ---        ┆ datetime[μ ┆ str        ┆ f64      │
│            ┆          ┆          ┆ str         ┆ str        ┆ s]         ┆            ┆          │
╞════════════╪══════════╪══════════╪═════════════╪════════════╪════════════╪════════════╪══════════╡
│ 12466550   ┆ 23998182 ┆ 30000153 ┆ Trauma SICU ┆ Trauma     ┆ 2174-09-29 ┆ 2174-10-01 ┆ 1.636921 │
│            ┆          ┆          ┆ (TSICU)     ┆ SICU       ┆ 12:09:00   ┆ 03:26:10   ┆          │
│            ┆          ┆          ┆             ┆ (TSICU)    ┆            ┆            ┆          │
│ 12466550   ┆ 23998182 ┆ 31460471 ┆ Trauma SICU ┆ Trauma     ┆ 2174-10-04 ┆ 2174-10-06 ┆ 2.061076 │
│            ┆          ┆          ┆ (TSICU)     ┆ SICU       ┆ 19:15:28   ┆ 20:43:25   ┆          │
│            ┆          ┆          ┆             ┆ (TSICU)    ┆            ┆            ┆          │
└────────────┴──────────┴──────────┴─────────────┴────────────┴────────────┴────────────┴──────────┘

In [ ]:
icustay[0]["intime"][0]

datetime.datetime(2174, 9, 29, 12, 9)

In [ ]:
crea_subject.with_columns(((pl.col("time") - icustay[0]["intime"][0])).alias("charttime"))

shape: (14, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ subject_i ┆ time      ┆ code      ┆ numeric_v ┆ … ┆ dataset  ┆ table     ┆ src_code  ┆ charttime │
│ d         ┆ ---       ┆ ---       ┆ alue      ┆   ┆ ---      ┆ ---       ┆ ---       ┆ ---       │
│ ---       ┆ datetime[ ┆ str       ┆ ---       ┆   ┆ str      ┆ str       ┆ str       ┆ duration[ │
│ i64       ┆ μs]       ┆           ┆ f32       ┆   ┆          ┆           ┆           ┆ μs]       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ 12466550  ┆ 2174-09-2 ┆ creatinin ┆ 1.2       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ -1h -53m  │
│           ┆ 9         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆           │
│           ┆ 10:16:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 12466550  ┆ 2174-09-2 ┆ creatinin ┆ 0.9       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 3h 28m    │
│           ┆ 9         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆           │
│           ┆ 15:37:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 12466550  ┆ 2174-09-3 ┆ creatinin ┆ 1.1       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 15h 25m   │
│           ┆ 0         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆           │
│           ┆ 03:34:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 12466550  ┆ 2174-10-0 ┆ creatinin ┆ 0.8       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 1d 17h    │
│           ┆ 1         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆ 26m       │
│           ┆ 05:35:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 12466550  ┆ 2174-10-0 ┆ creatinin ┆ 0.8       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 2d 19h    │
│           ┆ 2         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆ 11m       │
│           ┆ 07:20:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ 12466550  ┆ 2174-10-0 ┆ creatinin ┆ 1.1       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 7d 18h    │
│           ┆ 7         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆ 11m       │
│           ┆ 06:20:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 12466550  ┆ 2174-10-0 ┆ creatinin ┆ 1.0       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 8d 21h 6m │
│           ┆ 8         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆           │
│           ┆ 09:15:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 12466550  ┆ 2174-10-0 ┆ creatinin ┆ 1.1       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 9d 22h    │
│           ┆ 9         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆ 21m       │
│           ┆ 10:30:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 12466550  ┆ 2174-10-1 ┆ creatinin ┆ 0.9       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 10d 21h   │
│           ┆ 0         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆ 41m       │
│           ┆ 09:50:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
│ 12466550  ┆ 2174-10-1 ┆ creatinin ┆ 1.0       ┆ … ┆ mimic-iv ┆ labevents ┆ mimic-iv/ ┆ 11d 17h   │
│           ┆ 1         ┆ e//mg/dL  ┆           ┆   ┆          ┆           ┆ /3.1//lab ┆ 16m       │
│           ┆ 05:25:00  ┆           ┆           ┆   ┆          ┆           ┆ events//l ┆           │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ abe…      ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [ ]:
3 * 60 * 60 + 28 * 60

12480

In [ ]:
pl.scan_csv("/workspaces/example/data/physionet.org/files/mimiciv/3.1/icu/icustays.csv.gz").filter(pl.col("subject_id") == 12466550).collect()

shape: (2, 8)
┌────────────┬──────────┬──────────┬─────────────┬────────────┬────────────┬────────────┬──────────┐
│ subject_id ┆ hadm_id  ┆ stay_id  ┆ first_careu ┆ last_careu ┆ intime     ┆ outtime    ┆ los      │
│ ---        ┆ ---      ┆ ---      ┆ nit         ┆ nit        ┆ ---        ┆ ---        ┆ ---      │
│ i64        ┆ i64      ┆ i64      ┆ ---         ┆ ---        ┆ str        ┆ str        ┆ f64      │
│            ┆          ┆          ┆ str         ┆ str        ┆            ┆            ┆          │
╞════════════╪══════════╪══════════╪═════════════╪════════════╪════════════╪════════════╪══════════╡
│ 12466550   ┆ 23998182 ┆ 30000153 ┆ Trauma SICU ┆ Trauma     ┆ 2174-09-29 ┆ 2174-10-01 ┆ 1.636921 │
│            ┆          ┆          ┆ (TSICU)     ┆ SICU       ┆ 12:09:00   ┆ 03:26:10   ┆          │
│            ┆          ┆          ┆             ┆ (TSICU)    ┆            ┆            ┆          │
│ 12466550   ┆ 23998182 ┆ 31460471 ┆ Trauma SICU ┆ Trauma     ┆ 2174-10-04 ┆ 2174-10-06 ┆ 2.061076 │
│            ┆          ┆          ┆ (TSICU)     ┆ SICU       ┆ 19:15:28   ┆ 20:43:25   ┆          │
│            ┆          ┆          ┆             ┆ (TSICU)    ┆            ┆            ┆          │
└────────────┴──────────┴──────────┴─────────────┴────────────┴────────────┴────────────┴──────────┘

In [ ]:
for e in pl.scan_parquet("/workspaces/OpenICU-Example/output/project/datasets/extraction/metadata/codes.parquet").filter(pl.col("code").str.contains(".*?(Creatinine)//mg/dL") ).collect()["code"]:
    print(e)

mimic-iv//3.1//labevents//labevent//Creatinine//mg/dL
mimic-iv//3.1//labevents//labevent//Urine Creatinine//mg/dL

In [ ]:
x = crea.collect()

In [ ]:
x["code"].unique()

shape: (1,)
Series: 'code' [str]
[
	"creatinine//mg/dL"
]

In [ ]:
crea = crea.collect()

In [ ]:
crea

shape: (4_318_794, 8)
┌────────────┬────────────┬────────────┬────────────┬───────────┬──────────┬───────────┬───────────┐
│ subject_id ┆ time       ┆ code       ┆ numeric_va ┆ text_valu ┆ dataset  ┆ table     ┆ src_code  │
│ ---        ┆ ---        ┆ ---        ┆ lue        ┆ e         ┆ ---      ┆ ---       ┆ ---       │
│ i64        ┆ datetime[μ ┆ str        ┆ ---        ┆ ---       ┆ str      ┆ str       ┆ str       │
│            ┆ s]         ┆            ┆ f32        ┆ str       ┆          ┆           ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══════════╪══════════╪═══════════╪═══════════╡
│ 10000032   ┆ 2180-03-23 ┆ creatinine ┆ 0.4        ┆ 0.4       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 11:51:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 10000032   ┆ 2180-05-06 ┆ creatinine ┆ 0.3        ┆ 0.3       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 22:25:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 10000032   ┆ 2180-05-07 ┆ creatinine ┆ 0.3        ┆ 0.3       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 05:05:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 10000032   ┆ 2180-06-03 ┆ creatinine ┆ 0.4        ┆ 0.4       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 12:00:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 10000032   ┆ 2180-06-03 ┆ creatinine ┆ 0.4        ┆ 0.4       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 12:00:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …        ┆ …         ┆ …         │
│ 19999987   ┆ 2145-11-05 ┆ creatinine ┆ 0.9        ┆ 0.9       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 06:10:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 19999987   ┆ 2145-11-06 ┆ creatinine ┆ 1.0        ┆ 1.0       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 10:07:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 19999987   ┆ 2145-11-07 ┆ creatinine ┆ 0.9        ┆ 0.9       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 06:00:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 19999987   ┆ 2145-11-09 ┆ creatinine ┆ 0.9        ┆ 0.9       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 05:30:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 19999987   ┆ 2146-02-07 ┆ creatinine ┆ 1.1        ┆ 1.1       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 11:13:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
└────────────┴────────────┴────────────┴────────────┴───────────┴──────────┴───────────┴───────────┘

In [ ]:
crea = crea.with_columns(pl.col("time").dt.replace_time_zone("UTC"))

In [ ]:
crea = crea.filter(~pl.col("numeric_value").is_null(), pl.col("numeric_value").is_between(0, 15))

In [ ]:
ricu_crea = pl.read_parquet("./data/crea.parquet")

In [ ]:
ricu_crea

shape: (4_314_565, 5)
┌────────────┬────────────────┬──────┬─────────────────────────┬─────────────────────────┐
│ subject_id ┆ charttime      ┆ crea ┆ birthdate               ┆ charttime_origin        │
│ ---        ┆ ---            ┆ ---  ┆ ---                     ┆ ---                     │
│ i32        ┆ duration[ms]   ┆ f64  ┆ datetime[μs, UTC]       ┆ datetime[μs, UTC]       │
╞════════════╪════════════════╪══════╪═════════════════════════╪═════════════════════════╡
│ 10000032   ┆ 19075d 12h 51m ┆ 0.4  ┆ 2128-01-01 00:00:00 UTC ┆ 2180-03-23 11:51:00 UTC │
│ 10000032   ┆ 19119d 23h 25m ┆ 0.3  ┆ 2128-01-01 00:00:00 UTC ┆ 2180-05-06 22:25:00 UTC │
│ 10000032   ┆ 19120d 6h 5m   ┆ 0.3  ┆ 2128-01-01 00:00:00 UTC ┆ 2180-05-07 05:05:00 UTC │
│ 10000032   ┆ 19147d 13h     ┆ 0.4  ┆ 2128-01-01 00:00:00 UTC ┆ 2180-06-03 12:00:00 UTC │
│ 10000032   ┆ 19147d 13h     ┆ 0.4  ┆ 2128-01-01 00:00:00 UTC ┆ 2180-06-03 12:00:00 UTC │
│ …          ┆ …              ┆ …    ┆ …                       ┆ …                       │
│ 19999987   ┆ 21127d 7h 10m  ┆ 0.9  ┆ 2088-01-01 00:00:00 UTC ┆ 2145-11-05 06:10:00 UTC │
│ 19999987   ┆ 21128d 11h 7m  ┆ 1.0  ┆ 2088-01-01 00:00:00 UTC ┆ 2145-11-06 10:07:00 UTC │
│ 19999987   ┆ 21129d 7h      ┆ 0.9  ┆ 2088-01-01 00:00:00 UTC ┆ 2145-11-07 06:00:00 UTC │
│ 19999987   ┆ 21131d 6h 30m  ┆ 0.9  ┆ 2088-01-01 00:00:00 UTC ┆ 2145-11-09 05:30:00 UTC │
│ 19999987   ┆ 21221d 12h 13m ┆ 1.1  ┆ 2088-01-01 00:00:00 UTC ┆ 2146-02-07 11:13:00 UTC │
└────────────┴────────────────┴──────┴─────────────────────────┴─────────────────────────┘

In [ ]:
crea.head(2)

shape: (2, 8)
┌────────────┬────────────┬────────────┬────────────┬───────────┬──────────┬───────────┬───────────┐
│ subject_id ┆ time       ┆ code       ┆ numeric_va ┆ text_valu ┆ dataset  ┆ table     ┆ src_code  │
│ ---        ┆ ---        ┆ ---        ┆ lue        ┆ e         ┆ ---      ┆ ---       ┆ ---       │
│ i64        ┆ datetime[μ ┆ str        ┆ ---        ┆ ---       ┆ str      ┆ str       ┆ str       │
│            ┆ s, UTC]    ┆            ┆ f32        ┆ str       ┆          ┆           ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══════════╪══════════╪═══════════╪═══════════╡
│ 10000032   ┆ 2180-03-23 ┆ creatinine ┆ 0.4        ┆ 0.4       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 11:51:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆ UTC        ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 10000032   ┆ 2180-05-06 ┆ creatinine ┆ 0.3        ┆ 0.3       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 22:25:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆ UTC        ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
└────────────┴────────────┴────────────┴────────────┴───────────┴──────────┴───────────┴───────────┘

In [ ]:
x = pl.scan_parquet("output/project/datasets/extraction/data/labevents/labevent.parquet").filter(pl.col("subject_id") == 10026754).collect()
x["src_code"][0]

In [ ]:
x = crea.join(ricu_crea, right_on=["subject_id", "charttime_origin"], left_on=["subject_id", "time"], how="anti")
x

'mimic-iv//3.1//labevents//labevent//Creatinine//mg/dL'

In [ ]:
x.unique("text_value")

shape: (1, 8)
┌────────────┬────────────┬────────────┬────────────┬───────────┬──────────┬───────────┬───────────┐
│ subject_id ┆ time       ┆ code       ┆ numeric_va ┆ text_valu ┆ dataset  ┆ table     ┆ src_code  │
│ ---        ┆ ---        ┆ ---        ┆ lue        ┆ e         ┆ ---      ┆ ---       ┆ ---       │
│ i64        ┆ datetime[μ ┆ str        ┆ ---        ┆ ---       ┆ str      ┆ str       ┆ str       │
│            ┆ s, UTC]    ┆            ┆ f32        ┆ str       ┆          ┆           ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══════════╪══════════╪═══════════╪═══════════╡
│ 10026754   ┆ 2140-03-15 ┆ creatinine ┆ 0.8        ┆ ___       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 11:10:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆ UTC        ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
└────────────┴────────────┴────────────┴────────────┴───────────┴──────────┴───────────┴───────────┘

In [ ]:
crea.filter(pl.col("subject_id") == 10001725)

shape: (55, 8)
┌────────────┬────────────┬────────────┬────────────┬───────────┬──────────┬───────────┬───────────┐
│ subject_id ┆ time       ┆ code       ┆ numeric_va ┆ text_valu ┆ dataset  ┆ table     ┆ src_code  │
│ ---        ┆ ---        ┆ ---        ┆ lue        ┆ e         ┆ ---      ┆ ---       ┆ ---       │
│ i64        ┆ datetime[μ ┆ str        ┆ ---        ┆ ---       ┆ str      ┆ str       ┆ str       │
│            ┆ s, UTC]    ┆            ┆ f32        ┆ str       ┆          ┆           ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══════════╪══════════╪═══════════╪═══════════╡
│ 10001725   ┆ 2110-04-11 ┆ creatinine ┆ 0.8        ┆ 0.8       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 18:02:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆ UTC        ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 10001725   ┆ 2110-04-12 ┆ creatinine ┆ 0.8        ┆ 0.8       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 02:59:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆ UTC        ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 10001725   ┆ 2110-04-13 ┆ creatinine ┆ 0.9        ┆ 0.9       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 06:00:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆ UTC        ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 10001725   ┆ 2110-04-14 ┆ creatinine ┆ 0.9        ┆ 0.9       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 07:10:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆ UTC        ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 10001725   ┆ 2110-05-04 ┆ creatinine ┆ 0.9        ┆ 0.9       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 17:17:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆ UTC        ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …        ┆ …         ┆ …         │
│ 10001725   ┆ 2119-05-19 ┆ creatinine ┆ 0.8        ┆ 0.8       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 11:15:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆ UTC        ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 10001725   ┆ 2119-05-19 ┆ creatinine ┆ 0.8        ┆ 0.8       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 11:15:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆ UTC        ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 10001725   ┆ 2119-06-30 ┆ creatinine ┆ 0.9        ┆ 0.9       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 10:40:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆ UTC        ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 10001725   ┆ 2119-07-25 ┆ creatinine ┆ 0.8        ┆ 0.8       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 11:00:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆ UTC        ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
│ 10001725   ┆ 2119-08-25 ┆ creatinine ┆ 0.8        ┆ 0.8       ┆ mimic-iv ┆ labevents ┆ mimic-iv/ │
│            ┆ 13:10:00   ┆ //mg/dL    ┆            ┆           ┆          ┆           ┆ /3.1//lab │
│            ┆ UTC        ┆            ┆            ┆           ┆          ┆           ┆ events//l │
│            ┆            ┆            ┆            ┆           ┆          ┆           ┆ abe…      │
└────────────┴────────────┴────────────┴────────────┴───────────┴──────────┴───────────┴───────────┘

In [ ]:
ricu_crea.join(crea, left_on=["subject_id", "charttime_origin"], right_on=["subject_id", "time"], how="anti")

shape: (1, 5)
┌────────────┬───────────────┬──────┬─────────────────────────┬─────────────────────────┐
│ subject_id ┆ charttime     ┆ crea ┆ birthdate               ┆ charttime_origin        │
│ ---        ┆ ---           ┆ ---  ┆ ---                     ┆ ---                     │
│ i32        ┆ duration[ms]  ┆ f64  ┆ datetime[μs, UTC]       ┆ datetime[μs, UTC]       │
╞════════════╪═══════════════╪══════╪═════════════════════════╪═════════════════════════╡
│ 12458810   ┆ 27069d 2h 43m ┆ 1.0  ┆ 2057-01-01 00:00:00 UTC ┆ 2131-02-12 01:43:00 UTC │
└────────────┴───────────────┴──────┴─────────────────────────┴─────────────────────────┘