In [1]:
import polars as pl

# Raw Data

In [2]:
pl.read_csv("/workspaces/OpenICU.example/output/project/mimiciv-meds-notebook-run/raw_input/icu/chartevents.csv.gz")

shape: (668_862, 11)
┌────────────┬──────────┬──────────┬─────────────┬───┬─────────────┬──────────┬──────────┬─────────┐
│ subject_id ┆ hadm_id  ┆ stay_id  ┆ caregiver_i ┆ … ┆ value       ┆ valuenum ┆ valueuom ┆ warning │
│ ---        ┆ ---      ┆ ---      ┆ d           ┆   ┆ ---         ┆ ---      ┆ ---      ┆ ---     │
│ i64        ┆ i64      ┆ i64      ┆ ---         ┆   ┆ str         ┆ f64      ┆ str      ┆ i64     │
│            ┆          ┆          ┆ i64         ┆   ┆             ┆          ┆          ┆         │
╞════════════╪══════════╪══════════╪═════════════╪═══╪═════════════╪══════════╪══════════╪═════════╡
│ 10005817   ┆ 20626031 ┆ 32604416 ┆ 6770        ┆ … ┆ On          ┆ null     ┆ null     ┆ 0       │
│ 10005817   ┆ 20626031 ┆ 32604416 ┆ 6770        ┆ … ┆ 100         ┆ 100.0    ┆ %        ┆ 0       │
│ 10005817   ┆ 20626031 ┆ 32604416 ┆ 6770        ┆ … ┆ Atrial      ┆ null     ┆ null     ┆ 0       │
│            ┆          ┆          ┆             ┆   ┆ demand      ┆          ┆          ┆         │
│ 10005817   ┆ 20626031 ┆ 32604416 ┆ 6770        ┆ … ┆ Yes         ┆ null     ┆ null     ┆ 0       │
│ 10005817   ┆ 20626031 ┆ 32604416 ┆ 6770        ┆ … ┆ No          ┆ 0.0      ┆ null     ┆ 0       │
│ …          ┆ …        ┆ …        ┆ …           ┆ … ┆ …           ┆ …        ┆ …        ┆ …       │
│ 10019003   ┆ 29279905 ┆ 34107647 ┆ 60023       ┆ … ┆ .Care Plan  ┆ null     ┆ null     ┆ null    │
│            ┆          ┆          ┆             ┆   ┆ - Infection ┆          ┆          ┆         │
│ 10019003   ┆ 29279905 ┆ 34107647 ┆ 60023       ┆ … ┆ Diabetes    ┆ null     ┆ null     ┆ null    │
│            ┆          ┆          ┆             ┆   ┆ Mellitus    ┆          ┆          ┆         │
│            ┆          ┆          ┆             ┆   ┆ (DM), Type  ┆          ┆          ┆         │
│            ┆          ┆          ┆             ┆   ┆ I…          ┆          ┆          ┆         │
│ 10019003   ┆ 29279905 ┆ 34107647 ┆ 60023       ┆ … ┆ .Care Plan  ┆ null     ┆ null     ┆ null    │
│            ┆          ┆          ┆             ┆   ┆ - Coping    ┆          ┆          ┆         │
│ 10019003   ┆ 29279905 ┆ 34107647 ┆ 60023       ┆ … ┆ Chronic     ┆ null     ┆ null     ┆ null    │
│            ┆          ┆          ┆             ┆   ┆ obstructive ┆          ┆          ┆         │
│            ┆          ┆          ┆             ┆   ┆ pulmonary … ┆          ┆          ┆         │
│ 10019003   ┆ 29279905 ┆ 34107647 ┆ 60023       ┆ … ┆ .Care Plan  ┆ null     ┆ null     ┆ null    │
│            ┆          ┆          ┆             ┆   ┆ -           ┆          ┆          ┆         │
│            ┆          ┆          ┆             ┆   ┆ Alteration  ┆          ┆          ┆         │
│            ┆          ┆          ┆             ┆   ┆ in Bow…     ┆          ┆          ┆         │
└────────────┴──────────┴──────────┴─────────────┴───┴─────────────┴──────────┴──────────┴─────────┘

# PreMeds

In [3]:
pl.read_csv("/workspaces/OpenICU.example/output/project/mimiciv-meds-notebook-run/pre_MEDS/icu/chartevents.csv.gz")

shape: (668_862, 11)
┌────────────┬──────────┬──────────┬─────────────┬───┬─────────────┬──────────┬──────────┬─────────┐
│ subject_id ┆ hadm_id  ┆ stay_id  ┆ caregiver_i ┆ … ┆ value       ┆ valuenum ┆ valueuom ┆ warning │
│ ---        ┆ ---      ┆ ---      ┆ d           ┆   ┆ ---         ┆ ---      ┆ ---      ┆ ---     │
│ i64        ┆ i64      ┆ i64      ┆ ---         ┆   ┆ str         ┆ f64      ┆ str      ┆ i64     │
│            ┆          ┆          ┆ i64         ┆   ┆             ┆          ┆          ┆         │
╞════════════╪══════════╪══════════╪═════════════╪═══╪═════════════╪══════════╪══════════╪═════════╡
│ 10005817   ┆ 20626031 ┆ 32604416 ┆ 6770        ┆ … ┆ On          ┆ null     ┆ null     ┆ 0       │
│ 10005817   ┆ 20626031 ┆ 32604416 ┆ 6770        ┆ … ┆ 100         ┆ 100.0    ┆ %        ┆ 0       │
│ 10005817   ┆ 20626031 ┆ 32604416 ┆ 6770        ┆ … ┆ Atrial      ┆ null     ┆ null     ┆ 0       │
│            ┆          ┆          ┆             ┆   ┆ demand      ┆          ┆          ┆         │
│ 10005817   ┆ 20626031 ┆ 32604416 ┆ 6770        ┆ … ┆ Yes         ┆ null     ┆ null     ┆ 0       │
│ 10005817   ┆ 20626031 ┆ 32604416 ┆ 6770        ┆ … ┆ No          ┆ 0.0      ┆ null     ┆ 0       │
│ …          ┆ …        ┆ …        ┆ …           ┆ … ┆ …           ┆ …        ┆ …        ┆ …       │
│ 10019003   ┆ 29279905 ┆ 34107647 ┆ 60023       ┆ … ┆ .Care Plan  ┆ null     ┆ null     ┆ null    │
│            ┆          ┆          ┆             ┆   ┆ - Infection ┆          ┆          ┆         │
│ 10019003   ┆ 29279905 ┆ 34107647 ┆ 60023       ┆ … ┆ Diabetes    ┆ null     ┆ null     ┆ null    │
│            ┆          ┆          ┆             ┆   ┆ Mellitus    ┆          ┆          ┆         │
│            ┆          ┆          ┆             ┆   ┆ (DM), Type  ┆          ┆          ┆         │
│            ┆          ┆          ┆             ┆   ┆ I…          ┆          ┆          ┆         │
│ 10019003   ┆ 29279905 ┆ 34107647 ┆ 60023       ┆ … ┆ .Care Plan  ┆ null     ┆ null     ┆ null    │
│            ┆          ┆          ┆             ┆   ┆ - Coping    ┆          ┆          ┆         │
│ 10019003   ┆ 29279905 ┆ 34107647 ┆ 60023       ┆ … ┆ Chronic     ┆ null     ┆ null     ┆ null    │
│            ┆          ┆          ┆             ┆   ┆ obstructive ┆          ┆          ┆         │
│            ┆          ┆          ┆             ┆   ┆ pulmonary … ┆          ┆          ┆         │
│ 10019003   ┆ 29279905 ┆ 34107647 ┆ 60023       ┆ … ┆ .Care Plan  ┆ null     ┆ null     ┆ null    │
│            ┆          ┆          ┆             ┆   ┆ -           ┆          ┆          ┆         │
│            ┆          ┆          ┆             ┆   ┆ Alteration  ┆          ┆          ┆         │
│            ┆          ┆          ┆             ┆   ┆ in Bow…     ┆          ┆          ┆         │
└────────────┴──────────┴──────────┴─────────────┴───┴─────────────┴──────────┴──────────┴─────────┘

# After Sharding

In [4]:
pl.read_parquet("/workspaces/OpenICU.example/output/project/mimiciv-meds-notebook-run/MEDS_cohort/shard_events/icu/chartevents/[0-668862).parquet", glob=False)

shape: (668_862, 8)
┌────────────┬──────────┬──────────┬────────────┬────────┬───────────────────┬──────────┬──────────┐
│ subject_id ┆ hadm_id  ┆ stay_id  ┆ charttime  ┆ itemid ┆ value             ┆ valuenum ┆ valueuom │
│ ---        ┆ ---      ┆ ---      ┆ ---        ┆ ---    ┆ ---               ┆ ---      ┆ ---      │
│ i64        ┆ i64      ┆ i64      ┆ str        ┆ i64    ┆ str               ┆ f64      ┆ str      │
╞════════════╪══════════╪══════════╪════════════╪════════╪═══════════════════╪══════════╪══════════╡
│ 10005817   ┆ 20626031 ┆ 32604416 ┆ 2132-12-16 ┆ 225054 ┆ On                ┆ null     ┆ null     │
│            ┆          ┆          ┆ 00:00:00   ┆        ┆                   ┆          ┆          │
│ 10005817   ┆ 20626031 ┆ 32604416 ┆ 2132-12-16 ┆ 223769 ┆ 100               ┆ 100.0    ┆ %        │
│            ┆          ┆          ┆ 00:00:00   ┆        ┆                   ┆          ┆          │
│ 10005817   ┆ 20626031 ┆ 32604416 ┆ 2132-12-16 ┆ 223956 ┆ Atrial demand     ┆ null     ┆ null     │
│            ┆          ┆          ┆ 00:00:00   ┆        ┆                   ┆          ┆          │
│ 10005817   ┆ 20626031 ┆ 32604416 ┆ 2132-12-16 ┆ 224866 ┆ Yes               ┆ null     ┆ null     │
│            ┆          ┆          ┆ 00:00:00   ┆        ┆                   ┆          ┆          │
│ 10005817   ┆ 20626031 ┆ 32604416 ┆ 2132-12-16 ┆ 227341 ┆ No                ┆ 0.0      ┆ null     │
│            ┆          ┆          ┆ 00:00:00   ┆        ┆                   ┆          ┆          │
│ …          ┆ …        ┆ …        ┆ …          ┆ …      ┆ …                 ┆ …        ┆ …        │
│ 10019003   ┆ 29279905 ┆ 34107647 ┆ 2153-03-28 ┆ 220001 ┆ .Care Plan -      ┆ null     ┆ null     │
│            ┆          ┆          ┆ 10:49:28   ┆        ┆ Infection         ┆          ┆          │
│ 10019003   ┆ 29279905 ┆ 34107647 ┆ 2153-03-28 ┆ 220001 ┆ Diabetes Mellitus ┆ null     ┆ null     │
│            ┆          ┆          ┆ 10:49:28   ┆        ┆ (DM), Type I…     ┆          ┆          │
│ 10019003   ┆ 29279905 ┆ 34107647 ┆ 2153-03-28 ┆ 220001 ┆ .Care Plan -      ┆ null     ┆ null     │
│            ┆          ┆          ┆ 10:49:28   ┆        ┆ Coping            ┆          ┆          │
│ 10019003   ┆ 29279905 ┆ 34107647 ┆ 2153-03-28 ┆ 220001 ┆ Chronic           ┆ null     ┆ null     │
│            ┆          ┆          ┆ 10:49:28   ┆        ┆ obstructive       ┆          ┆          │
│            ┆          ┆          ┆            ┆        ┆ pulmonary …       ┆          ┆          │
│ 10019003   ┆ 29279905 ┆ 34107647 ┆ 2153-03-28 ┆ 220001 ┆ .Care Plan -      ┆ null     ┆ null     │
│            ┆          ┆          ┆ 10:49:28   ┆        ┆ Alteration in     ┆          ┆          │
│            ┆          ┆          ┆            ┆        ┆ Bow…              ┆          ┆          │
└────────────┴──────────┴──────────┴────────────┴────────┴───────────────────┴──────────┴──────────┘

# Splits and subject_sharding

In [5]:
pl.read_json("/workspaces/OpenICU.example/output/project/mimiciv-meds-notebook-run/MEDS_cohort/metadata/.shards.json")

shape: (1, 3)
┌────────────────────────┬─────────────────────────────────┬─────────────────────────────────┐
│ train/0                ┆ tuning/0                        ┆ held_out/0                      │
│ ---                    ┆ ---                             ┆ ---                             │
│ list[i64]              ┆ list[i64]                       ┆ list[i64]                       │
╞════════════════════════╪═════════════════════════════════╪═════════════════════════════════╡
│ [10022281, 10004235, … ┆ [10020740, 10038992, … 1002625… ┆ [10025463, 10019385, … 1002635… │
│ 1000445…               ┆                                 ┆                                 │
└────────────────────────┴─────────────────────────────────┴─────────────────────────────────┘

# Convert to Sharded events

In [7]:
pl.read_parquet("/workspaces/OpenICU.example/output/project/mimiciv-meds-notebook-run/MEDS_cohort/convert_to_sharded_events/train/0/icu/chartevents/[0-668862).parquet", glob=False)

shape: (584_247, 7)
┌────────────┬───────────────┬───────────────┬──────────────┬──────────────┬──────────┬────────────┐
│ subject_id ┆ code          ┆ time          ┆ numeric_valu ┆ text_value   ┆ hadm_id  ┆ icustay_id │
│ ---        ┆ ---           ┆ ---           ┆ e            ┆ ---          ┆ ---      ┆ ---        │
│ i64        ┆ str           ┆ datetime[μs]  ┆ ---          ┆ str          ┆ i64      ┆ i64        │
│            ┆               ┆               ┆ f64          ┆              ┆          ┆            │
╞════════════╪═══════════════╪═══════════════╪══════════════╪══════════════╪══════════╪════════════╡
│ 10005817   ┆ LAB//225054// ┆ 2132-12-16    ┆ null         ┆ On           ┆ 20626031 ┆ 32604416   │
│            ┆ UNK           ┆ 00:00:00      ┆              ┆              ┆          ┆            │
│ 10005817   ┆ LAB//223769// ┆ 2132-12-16    ┆ 100.0        ┆ null         ┆ 20626031 ┆ 32604416   │
│            ┆ %             ┆ 00:00:00      ┆              ┆              ┆          ┆            │
│ 10005817   ┆ LAB//223956// ┆ 2132-12-16    ┆ null         ┆ Atrial       ┆ 20626031 ┆ 32604416   │
│            ┆ UNK           ┆ 00:00:00      ┆              ┆ demand       ┆          ┆            │
│ 10005817   ┆ LAB//224866// ┆ 2132-12-16    ┆ null         ┆ Yes          ┆ 20626031 ┆ 32604416   │
│            ┆ UNK           ┆ 00:00:00      ┆              ┆              ┆          ┆            │
│ 10005817   ┆ LAB//227341// ┆ 2132-12-16    ┆ 0.0          ┆ No           ┆ 20626031 ┆ 32604416   │
│            ┆ UNK           ┆ 00:00:00      ┆              ┆              ┆          ┆            │
│ …          ┆ …             ┆ …             ┆ …            ┆ …            ┆ …        ┆ …          │
│ 10019003   ┆ LAB//220001// ┆ 2153-03-28    ┆ null         ┆ .Care Plan - ┆ 29279905 ┆ 34107647   │
│            ┆ UNK           ┆ 10:49:28      ┆              ┆ Infection    ┆          ┆            │
│ 10019003   ┆ LAB//220001// ┆ 2153-03-28    ┆ null         ┆ Diabetes     ┆ 29279905 ┆ 34107647   │
│            ┆ UNK           ┆ 10:49:28      ┆              ┆ Mellitus     ┆          ┆            │
│            ┆               ┆               ┆              ┆ (DM), Type   ┆          ┆            │
│            ┆               ┆               ┆              ┆ I…           ┆          ┆            │
│ 10019003   ┆ LAB//220001// ┆ 2153-03-28    ┆ null         ┆ .Care Plan - ┆ 29279905 ┆ 34107647   │
│            ┆ UNK           ┆ 10:49:28      ┆              ┆ Coping       ┆          ┆            │
│ 10019003   ┆ LAB//220001// ┆ 2153-03-28    ┆ null         ┆ Chronic      ┆ 29279905 ┆ 34107647   │
│            ┆ UNK           ┆ 10:49:28      ┆              ┆ obstructive  ┆          ┆            │
│            ┆               ┆               ┆              ┆ pulmonary …  ┆          ┆            │
│ 10019003   ┆ LAB//220001// ┆ 2153-03-28    ┆ null         ┆ .Care Plan - ┆ 29279905 ┆ 34107647   │
│            ┆ UNK           ┆ 10:49:28      ┆              ┆ Alteration   ┆          ┆            │
│            ┆               ┆               ┆              ┆ in Bow…      ┆          ┆            │
└────────────┴───────────────┴───────────────┴──────────────┴──────────────┴──────────┴────────────┘

# Merge to MEDS cohort

In [8]:
pl.read_parquet("/workspaces/OpenICU.example/output/project/mimiciv-meds-notebook-run/MEDS_cohort/merge_to_MEDS_cohort/train/0.parquet")

shape: (803_992, 25)
┌────────────┬────────────┬────────────┬───────────┬───┬────────────┬──────┬───────────┬───────────┐
│ subject_id ┆ code       ┆ time       ┆ insurance ┆ … ┆ link_order ┆ unit ┆ ordercate ┆ statusdes │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆   ┆ _id        ┆ ---  ┆ gorydescr ┆ cription  │
│ i64        ┆ str        ┆ datetime[μ ┆ str       ┆   ┆ ---        ┆ str  ┆ iption    ┆ ---       │
│            ┆            ┆ s]         ┆           ┆   ┆ i64        ┆      ┆ ---       ┆ str       │
│            ┆            ┆            ┆           ┆   ┆            ┆      ┆ str       ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══╪════════════╪══════╪═══════════╪═══════════╡
│ 10000032   ┆ GENDER//F  ┆ null       ┆ null      ┆ … ┆ null       ┆ null ┆ null      ┆ null      │
│ 10000032   ┆ MEDS_BIRTH ┆ 2128-01-01 ┆ null      ┆ … ┆ null       ┆ null ┆ null      ┆ null      │
│            ┆            ┆ 00:00:00   ┆           ┆   ┆            ┆      ┆           ┆           │
│ 10000032   ┆ LAB//51087 ┆ 2180-03-23 ┆ null      ┆ … ┆ null       ┆ null ┆ null      ┆ null      │
│            ┆ //UNK      ┆ 11:51:00   ┆           ┆   ┆            ┆      ┆           ┆           │
│ 10000032   ┆ LAB//50940 ┆ 2180-03-23 ┆ null      ┆ … ┆ null       ┆ null ┆ null      ┆ null      │
│            ┆ //UNK      ┆ 11:51:00   ┆           ┆   ┆            ┆      ┆           ┆           │
│ 10000032   ┆ LAB//51079 ┆ 2180-03-23 ┆ null      ┆ … ┆ null       ┆ null ┆ null      ┆ null      │
│            ┆ //UNK      ┆ 11:51:00   ┆           ┆   ┆            ┆      ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …          ┆ …    ┆ …         ┆ …         │
│ 10040025   ┆ MEDICATION ┆ 2148-02-05 ┆ null      ┆ … ┆ null       ┆ null ┆ null      ┆ null      │
│            ┆ //STOP//On ┆ 01:00:00   ┆           ┆   ┆            ┆      ┆           ┆           │
│            ┆ dansetron  ┆            ┆           ┆   ┆            ┆      ┆           ┆           │
│ 10040025   ┆ MEDICATION ┆ 2148-02-05 ┆ null      ┆ … ┆ null       ┆ null ┆ null      ┆ null      │
│            ┆ //STOP//Si ┆ 01:00:00   ┆           ┆   ┆            ┆      ┆           ┆           │
│            ┆ methicone  ┆            ┆           ┆   ┆            ┆      ┆           ┆           │
│ 10040025   ┆ MEDICATION ┆ 2148-02-05 ┆ null      ┆ … ┆ null       ┆ null ┆ null      ┆ null      │
│            ┆ //STOP//Bi ┆ 01:00:00   ┆           ┆   ┆            ┆      ┆           ┆           │
│            ┆ sacodyl    ┆            ┆           ┆   ┆            ┆      ┆           ┆           │
│ 10040025   ┆ MEDICATION ┆ 2148-02-05 ┆ null      ┆ … ┆ null       ┆ null ┆ null      ┆ null      │
│            ┆ //STOP//Gl ┆ 01:00:00   ┆           ┆   ┆            ┆      ┆           ┆           │
│            ┆ ucagon     ┆            ┆           ┆   ┆            ┆      ┆           ┆           │
│ 10040025   ┆ MEDS_DEATH ┆ 2148-02-07 ┆ null      ┆ … ┆ null       ┆ null ┆ null      ┆ null      │
│            ┆            ┆ 00:00:00   ┆           ┆   ┆            ┆      ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───┴────────────┴──────┴───────────┴───────────┘

# Extract code metadata

In [9]:
pl.read_parquet("/workspaces/OpenICU.example/output/project/mimiciv-meds-notebook-run/MEDS_cohort/extract_code_metadata/codes.parquet")

shape: (2_661, 6)
┌──────────────────┬──────────────────┬────────────┬───────────┬─────────────────┬─────────────────┐
│ code             ┆ possibly_cpt_cod ┆ itemid     ┆ valueuom  ┆ description     ┆ parent_codes    │
│ ---              ┆ e                ┆ ---        ┆ ---       ┆ ---             ┆ ---             │
│ str              ┆ ---              ┆ list[str]  ┆ list[str] ┆ str             ┆ list[str]       │
│                  ┆ list[str]        ┆            ┆           ┆                 ┆                 │
╞══════════════════╪══════════════════╪════════════╪═══════════╪═════════════════╪═════════════════╡
│ LAB//51239//UNK  ┆ [null]           ┆ ["51239"]  ┆ [null]    ┆ Lambda          ┆ ["LOINC/17224-7 │
│                  ┆                  ┆            ┆           ┆ lymphocytes/100 ┆ "]              │
│                  ┆                  ┆            ┆           ┆ lymphoc…        ┆                 │
│ DIAGNOSIS//ICD// ┆ [null]           ┆ [null]     ┆ [null]    ┆ Colostomy       ┆ ["ICD9CM/V44.3" │
│ 9//V443          ┆                  ┆            ┆           ┆ status          ┆ ]               │
│ DIAGNOSIS//ICD// ┆ [null]           ┆ [null]     ┆ [null]    ┆ Orthostatic     ┆ ["ICD10CM/I95.1 │
│ 10//I951         ┆                  ┆            ┆           ┆ hypotension     ┆ "]              │
│ DIAGNOSIS//ICD// ┆ [null]           ┆ [null]     ┆ [null]    ┆ Peripheral      ┆ ["ICD10CM/Z95.8 │
│ 10//Z95820       ┆                  ┆            ┆           ┆ vascular        ┆ 20"]            │
│                  ┆                  ┆            ┆           ┆ angioplast…     ┆                 │
│ DIAGNOSIS//ICD// ┆ [null]           ┆ [null]     ┆ [null]    ┆ Other fall on   ┆ ["ICD10CM/W18.3 │
│ 10//W1839XA      ┆                  ┆            ┆           ┆ same level,     ┆ 9XA"]           │
│                  ┆                  ┆            ┆           ┆ init…           ┆                 │
│ …                ┆ …                ┆ …          ┆ …         ┆ …               ┆ …               │
│ DIAGNOSIS//ICD// ┆ [null]           ┆ [null]     ┆ [null]    ┆ Alcoholic       ┆ ["ICD10CM/K70.1 │
│ 10//K7011        ┆                  ┆            ┆           ┆ hepatitis with  ┆ 1"]             │
│                  ┆                  ┆            ┆           ┆ ascit…          ┆                 │
│ INFUSION_START// ┆ [null]           ┆ ["221749"] ┆ [null]    ┆ phenylephrine   ┆ ["RxNorm/166637 │
│ 221749           ┆                  ┆            ┆           ┆ Injection       ┆ 1"]             │
│ LAB//50882//mEq/ ┆ [null]           ┆ ["50882"]  ┆ ["mEq/L"] ┆ Bicarbonate     ┆ ["LOINC/1963-8" │
│ L                ┆                  ┆            ┆           ┆ [Moles/volume]  ┆ ]               │
│                  ┆                  ┆            ┆           ┆ in …            ┆                 │
│ DIAGNOSIS//ICD// ┆ [null]           ┆ [null]     ┆ [null]    ┆ Other dysphagia ┆ ["ICD10CM/R13.1 │
│ 10//R1319        ┆                  ┆            ┆           ┆                 ┆ 9"]             │
│ DIAGNOSIS//ICD// ┆ [null]           ┆ [null]     ┆ [null]    ┆ Other and       ┆ ["ICD9CM/303.93 │
│ 9//30393         ┆                  ┆            ┆           ┆ unspecified     ┆ "]              │
│                  ┆                  ┆            ┆           ┆ alcohol …       ┆                 │
└──────────────────┴──────────────────┴────────────┴───────────┴─────────────────┴─────────────────┘

In [10]:
pl.read_parquet("/workspaces/OpenICU.example/output/project/mimiciv-meds-notebook-run/MEDS_cohort/extract_code_metadata/inputevents_to_rxnorm.parquet")

shape: (230, 4)
┌────────────────────────┬─────────────────────────────────┬────────┬────────────────────┐
│ code                   ┆ description                     ┆ itemid ┆ parent_codes       │
│ ---                    ┆ ---                             ┆ ---    ┆ ---                │
│ str                    ┆ str                             ┆ str    ┆ list[str]          │
╞════════════════════════╪═════════════════════════════════╪════════╪════════════════════╡
│ INFUSION_START//221906 ┆ norepinephrine Injection        ┆ 221906 ┆ ["RxNorm/1745276"] │
│ INFUSION_START//222168 ┆ propofol Injection              ┆ 222168 ┆ ["RxNorm/1808216"] │
│ INFUSION_START//221749 ┆ phenylephrine Injection         ┆ 221749 ┆ ["RxNorm/1666371"] │
│ INFUSION_START//221744 ┆ fentanyl Injection              ┆ 221744 ┆ ["RxNorm/1735002"] │
│ INFUSION_START//225166 ┆ potassium chloride Injection    ┆ 225166 ┆ ["RxNorm/1860131"] │
│ …                      ┆ …                               ┆ …      ┆ …                  │
│ INFUSION_END//229058   ┆ 6-aminocaproic acid Injectable… ┆ 229058 ┆ ["RxNorm/363495"]  │
│ INFUSION_END//225866   ┆ erythromycin Oral Solution      ┆ 225866 ┆ ["RxNorm/562280"]  │
│ INFUSION_END//229615   ┆ esomeprazole Injection [Nexium… ┆ 229615 ┆ ["RxNorm/1728039"] │
│ INFUSION_END//225860   ┆ clindamycin Oral Solution       ┆ 225860 ┆ ["RxNorm/562265"]  │
│ INFUSION_END//227524   ┆ magnesium sulfate Injection     ┆ 227524 ┆ ["RxNorm/1656665"] │
└────────────────────────┴─────────────────────────────────┴────────┴────────────────────┘

# Finalize MEDS metadata

In [11]:
pl.read_parquet("/workspaces/OpenICU.example/output/project/mimiciv-meds-notebook-run/MEDS_cohort/metadata/codes.parquet")

shape: (2_661, 6)
┌──────────────────┬──────────────────┬─────────────────┬─────────────────┬────────────┬───────────┐
│ code             ┆ description      ┆ parent_codes    ┆ possibly_cpt_co ┆ itemid     ┆ valueuom  │
│ ---              ┆ ---              ┆ ---             ┆ de              ┆ ---        ┆ ---       │
│ str              ┆ str              ┆ list[str]       ┆ ---             ┆ list[str]  ┆ list[str] │
│                  ┆                  ┆                 ┆ list[str]       ┆            ┆           │
╞══════════════════╪══════════════════╪═════════════════╪═════════════════╪════════════╪═══════════╡
│ LAB//51239//UNK  ┆ Lambda           ┆ ["LOINC/17224-7 ┆ [null]          ┆ ["51239"]  ┆ [null]    │
│                  ┆ lymphocytes/100  ┆ "]              ┆                 ┆            ┆           │
│                  ┆ lymphoc…         ┆                 ┆                 ┆            ┆           │
│ DIAGNOSIS//ICD// ┆ Colostomy status ┆ ["ICD9CM/V44.3" ┆ [null]          ┆ [null]     ┆ [null]    │
│ 9//V443          ┆                  ┆ ]               ┆                 ┆            ┆           │
│ DIAGNOSIS//ICD// ┆ Orthostatic      ┆ ["ICD10CM/I95.1 ┆ [null]          ┆ [null]     ┆ [null]    │
│ 10//I951         ┆ hypotension      ┆ "]              ┆                 ┆            ┆           │
│ DIAGNOSIS//ICD// ┆ Peripheral       ┆ ["ICD10CM/Z95.8 ┆ [null]          ┆ [null]     ┆ [null]    │
│ 10//Z95820       ┆ vascular         ┆ 20"]            ┆                 ┆            ┆           │
│                  ┆ angioplast…      ┆                 ┆                 ┆            ┆           │
│ DIAGNOSIS//ICD// ┆ Other fall on    ┆ ["ICD10CM/W18.3 ┆ [null]          ┆ [null]     ┆ [null]    │
│ 10//W1839XA      ┆ same level,      ┆ 9XA"]           ┆                 ┆            ┆           │
│                  ┆ init…            ┆                 ┆                 ┆            ┆           │
│ …                ┆ …                ┆ …               ┆ …               ┆ …          ┆ …         │
│ DIAGNOSIS//ICD// ┆ Alcoholic        ┆ ["ICD10CM/K70.1 ┆ [null]          ┆ [null]     ┆ [null]    │
│ 10//K7011        ┆ hepatitis with   ┆ 1"]             ┆                 ┆            ┆           │
│                  ┆ ascit…           ┆                 ┆                 ┆            ┆           │
│ INFUSION_START// ┆ phenylephrine    ┆ ["RxNorm/166637 ┆ [null]          ┆ ["221749"] ┆ [null]    │
│ 221749           ┆ Injection        ┆ 1"]             ┆                 ┆            ┆           │
│ LAB//50882//mEq/ ┆ Bicarbonate      ┆ ["LOINC/1963-8" ┆ [null]          ┆ ["50882"]  ┆ ["mEq/L"] │
│ L                ┆ [Moles/volume]   ┆ ]               ┆                 ┆            ┆           │
│                  ┆ in …             ┆                 ┆                 ┆            ┆           │
│ DIAGNOSIS//ICD// ┆ Other dysphagia  ┆ ["ICD10CM/R13.1 ┆ [null]          ┆ [null]     ┆ [null]    │
│ 10//R1319        ┆                  ┆ 9"]             ┆                 ┆            ┆           │
│ DIAGNOSIS//ICD// ┆ Other and        ┆ ["ICD9CM/303.93 ┆ [null]          ┆ [null]     ┆ [null]    │
│ 9//30393         ┆ unspecified      ┆ "]              ┆                 ┆            ┆           │
│                  ┆ alcohol …        ┆                 ┆                 ┆            ┆           │
└──────────────────┴──────────────────┴─────────────────┴─────────────────┴────────────┴───────────┘

# Finalize MEDS data

In [12]:
pl.read_parquet("/workspaces/OpenICU.example/output/project/mimiciv-meds-notebook-run/MEDS_cohort/data/train/0.parquet")

shape: (803_992, 25)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬──────┬───────────┬───────────┐
│ subject_id ┆ time       ┆ code       ┆ numeric_va ┆ … ┆ link_orde ┆ unit ┆ ordercate ┆ statusdes │
│ ---        ┆ ---        ┆ ---        ┆ lue        ┆   ┆ r_id      ┆ ---  ┆ gorydescr ┆ cription  │
│ i64        ┆ datetime[μ ┆ str        ┆ ---        ┆   ┆ ---       ┆ str  ┆ iption    ┆ ---       │
│            ┆ s]         ┆            ┆ f32        ┆   ┆ i64       ┆      ┆ ---       ┆ str       │
│            ┆            ┆            ┆            ┆   ┆           ┆      ┆ str       ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪══════╪═══════════╪═══════════╡
│ 10000032   ┆ null       ┆ GENDER//F  ┆ null       ┆ … ┆ null      ┆ null ┆ null      ┆ null      │
│ 10000032   ┆ 2128-01-01 ┆ MEDS_BIRTH ┆ null       ┆ … ┆ null      ┆ null ┆ null      ┆ null      │
│            ┆ 00:00:00   ┆            ┆            ┆   ┆           ┆      ┆           ┆           │
│ 10000032   ┆ 2180-03-23 ┆ LAB//51087 ┆ null       ┆ … ┆ null      ┆ null ┆ null      ┆ null      │
│            ┆ 11:51:00   ┆ //UNK      ┆            ┆   ┆           ┆      ┆           ┆           │
│ 10000032   ┆ 2180-03-23 ┆ LAB//50940 ┆ null       ┆ … ┆ null      ┆ null ┆ null      ┆ null      │
│            ┆ 11:51:00   ┆ //UNK      ┆            ┆   ┆           ┆      ┆           ┆           │
│ 10000032   ┆ 2180-03-23 ┆ LAB//51079 ┆ null       ┆ … ┆ null      ┆ null ┆ null      ┆ null      │
│            ┆ 11:51:00   ┆ //UNK      ┆            ┆   ┆           ┆      ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …    ┆ …         ┆ …         │
│ 10040025   ┆ 2148-02-05 ┆ MEDICATION ┆ null       ┆ … ┆ null      ┆ null ┆ null      ┆ null      │
│            ┆ 01:00:00   ┆ //STOP//On ┆            ┆   ┆           ┆      ┆           ┆           │
│            ┆            ┆ dansetron  ┆            ┆   ┆           ┆      ┆           ┆           │
│ 10040025   ┆ 2148-02-05 ┆ MEDICATION ┆ null       ┆ … ┆ null      ┆ null ┆ null      ┆ null      │
│            ┆ 01:00:00   ┆ //STOP//Si ┆            ┆   ┆           ┆      ┆           ┆           │
│            ┆            ┆ methicone  ┆            ┆   ┆           ┆      ┆           ┆           │
│ 10040025   ┆ 2148-02-05 ┆ MEDICATION ┆ null       ┆ … ┆ null      ┆ null ┆ null      ┆ null      │
│            ┆ 01:00:00   ┆ //STOP//Bi ┆            ┆   ┆           ┆      ┆           ┆           │
│            ┆            ┆ sacodyl    ┆            ┆   ┆           ┆      ┆           ┆           │
│ 10040025   ┆ 2148-02-05 ┆ MEDICATION ┆ null       ┆ … ┆ null      ┆ null ┆ null      ┆ null      │
│            ┆ 01:00:00   ┆ //STOP//Gl ┆            ┆   ┆           ┆      ┆           ┆           │
│            ┆            ┆ ucagon     ┆            ┆   ┆           ┆      ┆           ┆           │
│ 10040025   ┆ 2148-02-07 ┆ MEDS_DEATH ┆ null       ┆ … ┆ null      ┆ null ┆ null      ┆ null      │
│            ┆ 00:00:00   ┆            ┆            ┆   ┆           ┆      ┆           ┆           │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴──────┴───────────┴───────────┘